using AdminApi.AutoGeneratedModel;
using AdminApi.Models.DataManager;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdminApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly AccountManager _repo;
        public AccountController( AccountManager repo)
        {
            _repo = repo;
        }

        [HttpGet("{id}")]
        public IEnumerable<Account> GetAccountsForCustomer(int id)
        {
            return _repo.FindByCondition(x => x.CustomerId == id);
        }
    }
}
