using AdminApi.AutoGeneratedModel;
using AdminApi.Models.DataManager;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AdminApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CustomerController : ControllerBase
    {
        private readonly CustomerManager _repo;

        public CustomerController(CustomerManager repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IEnumerable<Customer> GetAll()
        {
            return _repo.GetAll();
        }

        // GET api/customer/2100
        [HttpGet("{id}")]
        public Customer Get(int id)
        {
            return _repo.Get(id);
        }
    }
}
