using AdminApi.AutoGeneratedModel;
using AdminApi.Models.DataManager;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace AdminApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TransactionController : ControllerBase
    {
        private readonly TransactionManager _repo;

        public TransactionController(TransactionManager repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IEnumerable<Transaction> Get()
        {
            return _repo.GetAll();
        }

        [HttpGet("{id}")]
        public IEnumerable<Transaction> GetTransactions(int id, DateTime? fromDate = null, DateTime? toDate = null)
        {
            return _repo.GetTransactions(id, fromDate, toDate);
        }
    }
}
