using AdminApi.AutoGeneratedModel;
using AdminApi.Models.Repository;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;

namespace AdminApi.Models.DataManager
{
    public class BillPayManager : DataRepository<BillPay, int>, IBillPayRepository
    {
        private readonly ILogger<BillPayManager> _logger;
        public BillPayManager(McbaContext context, ILogger<BillPayManager> logger) : base(context)
        {
            _logger = logger;
        }

        public async Task BlockBillPayAsync(int billPayID, bool blockFlag)
        {
            var billPay = Get(billPayID);
            if(billPay is null)
            {
                _logger.LogError($"Unable to get bill pay with id: {billPayID}");
            }

            if(billPay.IsBlocked == blockFlag)
            {
                _logger.LogInformation($"Bill pay already set to {blockFlag}");
                return;
            }

            billPay.IsBlocked = blockFlag;

            await _context.SaveChangesAsync().ConfigureAwait(false);
        }

    }
}
