using AdminApi.AutoGeneratedModel;
using AdminApi.Models.Repository;
using System;
using System.Threading.Tasks;

namespace AdminApi.Models.DataManager
{
    public class BillPayManager : DataRepository<BillPay, int>, IBillPayRepository
    {
        public BillPayManager(McbaContext context) : base(context)
        { }

        public async Task BlockBillPayAsync(int billPayID)
        {
            var billPay = Get(billPayID);
            if(billPay is null)
            {
                throw new NullReferenceException(nameof(billPay));
            }

            billPay.IsBlocked = true;

            await _context.SaveChangesAsync().ConfigureAwait(false);
        }

        public async Task UnblockBillPayAsync(int billPayID)
        {
            var billPay = Get(billPayID);
            if (billPay is null)
            {
                throw new NullReferenceException(nameof(billPay));
            }

            billPay.IsBlocked = false;
            await _context.SaveChangesAsync().ConfigureAwait(false);

        }
    }
}
