using AdminApi.AutoGeneratedModel;

namespace AdminApi.Models.DataManager
{
    public class CustomerManager : DataRepository<Customer, int>
    {
        public CustomerManager(McbaContext context) : base(context)
        { }
    }
}
