using AdminApi.AutoGeneratedModel;
using AdminApi.Models.Repository;
using System.Threading.Tasks;

namespace AdminApi.Models.DataManager
{
    public class UserAccountManager : DataRepository<Login, string>, IUserAccountRepository
    {
        public UserAccountManager(McbaContext context) : base(context) 
        { }

        public async Task LockAccountAsync(string loginID)
        {
            var login = Get(loginID);
            login.IsLocked = true;

            await _context.SaveChangesAsync().ConfigureAwait(false);

            // Unlock after a minute.
            await Task.Delay(1000);
            login.IsLocked = false;
            await _context.SaveChangesAsync().ConfigureAwait(false);
        }
    }
}
