using AdminApp.AutoGeneratedModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AdminApp.ViewModels
{
    public class BillPayViewModel
    {
        [Display(Name = "Bill Pay Id")]
        public int BillPayID { get; set; }

        [Display(Name = "Bill Pays")]
        public List<BillPay> BillPays { get; set; }
    }
}
