using AdminApp.AutoGeneratedModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdminApp.ViewModels
{
    public class TransactionViewModel
    {
        [Display(Name = "Customer ID")]
        public int CustomerID { get; set; }

        [Display(Name = "From Date"), DataType(DataType.Date)]
        public DateTime? FromDate { get; set; }

        [Display(Name = "To Date"), DataType(DataType.Date)]
        public DateTime? ToDate { get; set; }

        public List<Account> Accounts { get; set; }

        public List<Transaction> Transactions { get; set; }
    }
}
