using AdminApp.AutoGeneratedModel;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdminApp.ViewModels
{
    public class UserAccountViewModel
    {
        [Display(Name = "Customer ID")]
        public int CustomerID { get; set; }
        public List<Customer> Customers { get; set; }
    }
}
