using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdminApi.AutoGeneratedModel
{
    public partial class Payee
    {
        public Payee()
        {
            BillPays = new HashSet<BillPay>();
        }

        [Key]
        [Column("PayeeID")]
        public int PayeeId { get; set; }
        [Required]
        [StringLength(50)]
        public string PayeeName { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        [StringLength(40)]
        public string City { get; set; }
        [StringLength(20)]
        public string State { get; set; }
        [StringLength(10)]
        public string PostCode { get; set; }
        [Required]
        [StringLength(15)]
        public string Phone { get; set; }

        [InverseProperty(nameof(BillPay.Payee))]
        public virtual ICollection<BillPay> BillPays { get; set; }
    }
}
