using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdminApi.AutoGeneratedModel
{
    [Index(nameof(AccountNumber), Name = "IX_Transactions_AccountNumber")]
    [Index(nameof(DestinationAccountNumber), Name = "IX_Transactions_DestinationAccountNumber")]
    public partial class Transaction
    {
        [Key]
        [Column("TransactionID")]
        public int TransactionId { get; set; }
        public int TransactionType { get; set; }
        public int AccountNumber { get; set; }
        public int? DestinationAccountNumber { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        [StringLength(255)]
        public string Comment { get; set; }
        public DateTime TransactionTimeUtc { get; set; }

        [ForeignKey(nameof(AccountNumber))]
        [InverseProperty(nameof(Account.TransactionAccountNumberNavigations))]
        public virtual Account AccountNumberNavigation { get; set; }
        [ForeignKey(nameof(DestinationAccountNumber))]
        [InverseProperty(nameof(Account.TransactionDestinationAccountNumberNavigations))]
        public virtual Account DestinationAccountNumberNavigation { get; set; }
    }
}
