using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdminApp.AutoGeneratedModel
{
    [Table("BillPay")]
    [Index(nameof(AccountNumber), Name = "IX_BillPay_AccountNumber")]
    [Index(nameof(PayeeId), Name = "IX_BillPay_PayeeID")]
    public partial class BillPay
    {
        [Key]
        [Column("BillPayID")]
        public int BillPayId { get; set; }
        [Column("PayeeID")]
        public int PayeeId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Amount { get; set; }
        public DateTime ScheduledDate { get; set; }
        public int Period { get; set; }
        public DateTime ModifyDate { get; set; }
        public int AccountNumber { get; set; }
        [Required]
        public bool? IsBlocked { get; set; }

        [ForeignKey(nameof(AccountNumber))]
        [InverseProperty(nameof(Account.BillPays))]
        public virtual Account AccountNumberNavigation { get; set; }
        [ForeignKey(nameof(PayeeId))]
        [InverseProperty("BillPays")]
        public virtual Payee Payee { get; set; }
    }
}
