using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdminApp.AutoGeneratedModel
{
    public partial class Customer
    {
        public Customer()
        {
            Accounts = new HashSet<Account>();
            Logins = new HashSet<Login>();
        }

        [Key]
        [Column("CustomerID")]
        public int CustomerId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("TFN")]
        [StringLength(11)]
        public string Tfn { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        [StringLength(40)]
        public string City { get; set; }
        [StringLength(20)]
        public string State { get; set; }
        [StringLength(10)]
        public string PostCode { get; set; }
        [StringLength(15)]
        public string Phone { get; set; }

        [InverseProperty(nameof(Account.Customer))]
        public virtual ICollection<Account> Accounts { get; set; }
        [InverseProperty(nameof(Login.Customer))]
        public virtual ICollection<Login> Logins { get; set; }
    }
}
