using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdminApp.AutoGeneratedModel
{
    [Index(nameof(CustomerId), Name = "IX_Logins_CustomerID")]
    public partial class Login
    {
        [Key]
        [Column("LoginID")]
        [StringLength(8)]
        public string LoginId { get; set; }
        [Column("CustomerID")]
        public int CustomerId { get; set; }
        [Required]
        [StringLength(64)]
        public string PasswordHash { get; set; }
        public DateTime ModifyDate { get; set; }
        [Required]
        public bool? IsLocked { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("Logins")]
        public virtual Customer Customer { get; set; }
    }
}
