using AdminApp.AutoGeneratedModel;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AdminApp.Interfaces
{
    public interface IAccountService
    {
        Task<List<Account>> GetAccountsFromCustomerAsync(int customerID);
    }
}
