using AdminApp.AutoGeneratedModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdminApp.Interfaces
{
    public interface IBillPayService
    {
        Task BlockBillPayAsync(int billPayId);
        Task<List<BillPay>> GetAllBillPaysAsync();
        Task UnblockBillPayAsync(int billPayId);
    }
}
