using AdminApi.AutoGeneratedModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdminApi.Models.Repository
{
    public interface IBillPayRepository : IDataRepository<BillPay, int>
    {
        /// <summary>
        /// Block or unblock a bill pay.
        /// </summary>
        /// <param name="billPayID">Id of bill pay to block/unblock</param>
        /// <param name="blockFlag">True -> block, False -> Unblock</param>
        public Task BlockBillPayAsync(int billPayID, bool blockFlag);
    }
}
